version: 2
updates:
    - package-ecosystem: gitsubmodule
      directory: /
      schedule:
       interval: daily
       time: '09:00'
       timezone: Asia/Ho_Chi_Minh

    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: daily
        time: '09:00'
        timezone: Asia/Manila
