name: Build Soggy on push
on:
  push:
    paths:
      - soggy
      - .github/workflows/build-on-push.yaml
    branches-ignore:
      - dependabot/**

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false

      - name: Move Soggy src
        shell: bash
        run: mv -v ./soggy/* .
          
      - name: install dependencies (vcpkg)
        run: vcpkg install protobuf lua[cpp]:x64-windows
        
      - name: Prepare for build
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          
      - name: Build time
        run: cmake --build build -j8
