name: Build Soggy on pull request
on:
  pull_request_target:
    paths:
      - soggy
      - .github/workflows/build-on-push.yaml
      - .github/workflows/build-on-pull-request.yaml
      
jobs:
  build:
    runs-on: windows-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'phanhoang1366'
    
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            submodules: true
            ref: ${{ github.event.pull_request.head.ref }}
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            persist-credentials: false

        - name: Get current date & time before build
          id: date-time-before
          shell: bash
          run: echo date-time=$(date +'%Y-%m-%d %H:%M') >> $GITHUB_OUTPUT

        - name: Install dependencies (vcpkg)
          run: vcpkg install protobuf lua[cpp]:x64-windows
          
        - name: Patch
          shell: bash
          run: |
           cd soggy
           sed '13a\string(REPLACE "/O2" "/Od" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")' CMakeLists.txt > CMakeLists2.txt
           rm CMakeLists.txt
           mv CMakeLists2.txt CMakeLists.txt

        - name: Prepare for build (No optimization)
          run: |
            cd soggy
            cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="/Od" -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"
        - name: Build time
          run: |
            cd soggy
            cmake --build build -j8 --config Release -- /p:Optimize=false
            cd build/Release/
            7z a soggy_exec_rel.7z * -mx9
        - name: Get current date & time after build
          id: date-time-after
          shell: bash
          run: |
            echo date-time=$(date +'%Y-%m-%d %H:%M') >> $GITHUB_OUTPUT
            echo date-time-tag=$(date +'%Y-%m-%d-%H-%M') >> $GITHUB_OUTPUT
        - name: Upload Soggy Release
          uses: actions/upload-artifact@v3
          with:
            name: soggy-exec-rel
            path: soggy/build/Release/soggy_exec_rel.7z

    outputs:
        date-time-before: ${{ steps.date-time-before.outputs.date-time }}
        date-time-after: ${{ steps.date-time-after.outputs.date-time }}
        date-time-after-tag: ${{ steps.date-time-after.outputs.date-time-tag }}
        
  archive-rel:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Soggy build
        uses: actions/download-artifact@v3
        with:
          name: soggy-exec-rel
          
      - name: Download all dependencies
        run: |
          7z x soggy_exec_rel.7z
          rm soggy_exec_rel.7z
          wget https://github.com/LDAsuku/soggy/raw/mistress/dispatch.py
          wget https://github.com/LDAsuku/soggy/raw/mistress/soggy_cat.png
          echo "mitmdump.exe -p 8080 -s \"proxy.py\"" >> proxy.bat
          wget https://snapshots.mitmproxy.org/9.0.1/mitmproxy-9.0.1-windows.zip
          unzip mitmproxy-9.0.1-windows.zip mitmdump.exe 
          rm mitmproxy-9.0.1-windows.zip
          wget https://github.com/phanhoang1366/soggy-autobuilds/raw/main/proxy.py
          wget https://github.com/phanhoang1366/soggy-autobuilds/raw/main/proxy_config.py
          git clone https://codeberg.org/LDA_suku/soggy_resources.git resources
          
      - name: Compress with 7-Zip Soggy Full version (release)
        run: 7z a soggy_full_rel.7z * -mx9
      
      - name: Upload Soggy full version
        uses: actions/upload-artifact@v3
        with:
          name: soggy-7z-full-rel
          path: soggy_full_rel.7z
        
          
  release:
    needs: [build, archive-rel]
    runs-on: ubuntu-latest
    steps:
      - name: Download Soggy archive (Release)
        uses: actions/download-artifact@v3
        with:
          name: soggy-7z-full-rel
      
      - name: Download Soggy executable only (Release)
        uses: actions/download-artifact@v3
        with:
          name: soggy-exec-rel
                 
      - name: Release
        run: |
          gh release create "a-${{ needs.build.outputs.date-time-after-tag }}" \
          "soggy_full_rel.7z" \
          "soggy_exec_rel.7z" \
          -n "Soggy built on ${{ needs.build.outputs.date-time-after }} started at ${{ needs.build.outputs.date-time-before }}" \
          -p -t "${{ needs.build.outputs.date-time-after }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
